name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build portable version
      run: nix build .#waytemp-distrib
    
    - name: Test binary
      run: |
        ldd ./result/bin/waytemp
        ls -la ./result/bin/waytemp

    - name: Create release archive
      if: github.event_name == 'release'
      run: |
        VERSION=$GITHUB_REF_NAME
        echo "Building release for version: $VERSION"

        mkdir -p waytemp-release/{bin,lib}
        cp result/bin/waytemp waytemp-release/bin/
        cp result/lib/libwaytemp_core.so waytemp-release/lib/
        cp README.org waytemp-release/
        cp LICENSE.lisp waytemp-release/
        tar -czf waytemp-${VERSION}-x86_64-linux.tar.gz waytemp-release/

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./waytemp-${{ github.ref_name }}-x86_64-linux.tar.gz
        asset_name: waytemp-${{ github.ref_name }}-x86_64-linux.tar.gz
        asset_content_type: application/gzip
